### ISSUE TITLE
💡 Feature Request - Add documentation regarding pre-req for bicep-lz-vending

### ISSUE THREAD

**Issue by reduards** [Azure/bicep-lz-vending#24]
## Describe the solution you'd like

Add some of our documentation from enterprise scale, AzOps etc and modifying it. For example the access needed for the SPN to create subscriptions:
https://github.com/Azure/Enterprise-Scale/wiki/Create-Landingzones

**Comment by jtracey93** [comment]
Hey @reduards,

Is what is documented here, https://github.com/azure/bicep-lz-vending/wiki/permissions,already not sufficient?

If not happy to update just let us know what 👍

**Comment by reduards** [comment]
I somehow missed this, my bad. Will go ahead and close this one.
