### ISSUE TITLE
🪲 Bug Report - Role assignments not working when VNET is not created

### ISSUE THREAD

**Issue by onurmicoogullari** [Azure/bicep-lz-vending#37]
## Description
We are trying to create a new subscription using our lz-vending-module CD pipeline, under the "Sandbox" archetype, without a VNET and all of its related configuration/resources. Everything seems to work fine, except our role assignments seems to be completely ignored.

We have used the same pipeline before to create other subscriptions under "Corp" archetype with the only difference being that we provision those with a Spoke VNet peered to our Hub. In those scenarios, the role assignments works just fine.

Also, if I search for "roleAssignments" in the pipeline output, I can find outputs from the subscriptions containing VNets but nothing for the one without a VNet.

I did some troubleshooting in the bicep scripts and I'm guessing that this is the reason of this behaviour (**src > self > subResourceWrapper > deploy.bicep**):

> module createLzRoleAssignments '../../carml/v0.6.0/Microsoft.Authorization/roleAssignments/deploy.bicep' = [for assignment in roleAssignments: if (roleAssignmentEnabled && !empty(roleAssignments)) {
>   **dependsOn: [
>     createResourceGroupForLzNetworking
>   ]**
>   name: take('${deploymentNames.createLzRoleAssignments}-${uniqueString(assignment.principalId, assignment.definition, assignment.relativeScope)}', 64)
>   params: {
>     location: virtualNetworkLocation
>     principalId: assignment.principalId
>     roleDefinitionIdOrName: assignment.definition
>     subscriptionId: subscriptionId
>     resourceGroupName: (contains(assignment.relativeScope, '/resourceGroups/') ? split(assignment.relativeScope, '/')[2] : '')
>     enableDefaultTelemetry: enableTelemetryForCarml
>   }
> }]

From what I understand, this means that the role assignments are dependent on the VNet resource group creation. Problem is, we don't provision a VNet or any of its associated resources during deployment, since this is a sandbox subscription. Seems odd that there would have to be a relation between these two things. Is this really the intended behaviour?

## To Reproduce
Use the following parameter file to reproduce. Make sure to replace the placeholders.
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "subscriptionAliasEnabled": {
            "value": true
        },
        "subscriptionDisplayName": {
            "value": "ALZ Example Dev"
        },
        "subscriptionAliasName": {
            "value": "ALZ-Example-Dev"
        },
        "subscriptionBillingScope": {
            "value": "providers/Microsoft.Billing/billingAccounts/XXXXXXXX/enrollmentAccounts/XXXXXX"
        },
        "subscriptionWorkload": {
            "value": "DevTest"
        },
        "existingSubscriptionId": {
            "value": ""
        },
        "subscriptionManagementGroupAssociationEnabled": {
            "value": true
        },
        "subscriptionManagementGroupId": {
            "value": "lz-sandbox"
        },
        "subscriptionTags": {
            "value": {}
        },
        "virtualNetworkEnabled": {
            "value": false
        },
        "virtualNetworkResourceGroupName": {
            "value": ""
        },
        "virtualNetworkResourceGroupTags": {
            "value": {}
        },
        "virtualNetworkResourceGroupLockEnabled": {
            "value": false
        },
        "virtualNetworkLocation": {
            "value": ""
        },
        "virtualNetworkName": {
            "value": ""
        },
        "virtualNetworkTags": {
            "value": {}
        },
        "virtualNetworkAddressSpace": {
            "value": []
        },
        "virtualNetworkDnsServers": {
            "value": []
        },
        "virtualNetworkDdosPlanId": {
            "value": ""
        },
        "virtualNetworkPeeringEnabled": {
            "value": false
        },
        "hubNetworkResourceId": {
            "value": ""
        },
        "virtualNetworkUseRemoteGateways": {
            "value": false
        },
        "virtualNetworkVwanAssociatedRouteTableResourceId": {
            "value": ""
        },
        "virtualNetworkVwanPropagatedRouteTablesResourceIds": {
            "value": []
        },
        "virtualNetworkVwanPropagatedLabels": {
            "value": []
        },
        "roleAssignmentEnabled": {
            "value": true
        },
        "roleAssignments": {
            "value": [
                {
                    "principalId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                    "definition": "/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635",
                    "relativeScope": ""
                }
            ]
        },
        "disableTelemetry": {
            "value": true
        }
    }
}
```

## Expected behaviour
My expectation is that role assignments should be applied during provisioning, whether I choose to include a VNet or not.

**Comment by jtracey93** [comment]
Thanks for reporting @onurmicoogullari, good spot and find.

I will investigate, thanks for your help here also on your own debugging efforts, and publish a fix very shortly.

Thanks

Jack

**Comment by onurmicoogullari** [comment]
That was fast. Thanks @jtracey93!

**Comment by jtracey93** [comment]
no worries @onurmicoogullari just about to merge the PR.

Out of interest how are you consuming the module? By cloning the repo or from the public Bicep registry?

**Comment by onurmicoogullari** [comment]
We cloned the repo, so we'll have to pull down and merge your changes. Shouldn't be a big deal though since the only changes we've made in our private copy is adding a pipeline and LZ parameter files. We're using Azure DevOps as platform for our Azure LZ stuff.
