### ISSUE TITLE
🪲 Bug Report - Duplicate module identifier in example 4

### ISSUE THREAD

**Issue by modbase** [Azure/bicep-lz-vending#48]
## Describe the bug

[Example 4](https://github.com/azure/bicep-lz-vending/wiki/Example-4-Multiple-VNets-In-Same-Subscription) uses the same identifier for the modules twice. The second module should be renamed to for example `createSubAndSecondVnet `

https://github.com/Azure/bicep-lz-vending/blob/acb80e1ae7341cf3e2bffd167971b1d072812280/docs/wiki/Example-4-Multiple-VNets-In-Same-Subscription.md?plain=1#L40

**Comment by jtracey93** [comment]
Thanks for raising @modbase, would like to create a PR to resolve this?
