### ISSUE TITLE
🪲 Bug Report - Code does not work with vWAN routing intent enabled

### ISSUE THREAD

**Issue by MilesCameron-DMs** [Azure/bicep-lz-vending#54]
## Describe the bug

I have found the code passes an object over for the routing configuration of the VNET connection despite the values of the routing configuration being empty.

This fails as it should be passing over a null or empty value when routing intent is enabled:

```json
Routing configuration for Connection /subscriptions/<SUBGUID>/resourceGroups/<RESOURCEGROUP>/providers/Microsoft.Network/virtualHubs/<VIRTUALHUB>/hubVirtualNetworkConnections/<VIRTUALNETWORKCONNECTION> conflicts with Routing Intent /subscriptions/<SUBGUID>/resourceGroups/<RESOURCEGROUP>/providers/Microsoft.Network/virtualHubs/<VIRTUALHUB>/routingIntent/hubRoutingIntent. Leave Routing configuration empty to auto-populate.
```

The VWAN VNET connection is expecting an object for routingConfiguration and in the existing code the following values should not be set when routing intent is enabled:

```json

"virtualNetworkVwanAssociatedRouteTableResourceId": {
        "value": ""
      },
      "virtualNetworkVwanPropagatedRouteTablesResourceIds": {
        "value": []
      },
      "virtualNetworkVwanPropagatedLabels": {
        "value": []
      }
```

When these values are constructed into the object in the `src\self\subResourceWrapper\deploy.bicep` file:

```bicep

associatedRouteTable: {
        id: virtualWanHubConnectionAssociatedRouteTable
      }
      propagatedRouteTables: {
        ids: virtualWanHubConnectionPropogatedRouteTables
        labels: virtualWanHubConnectionPropogatedLabels
        }

```

It still passes an object and results in the error above.

To get round this is have introduced a boolean parameter for routingIntent and amended the `src\self\subResourceWrapper\deploy.bicep`  as follows:

```bicep
routingConfiguration: !routingIntent ? { 
      associatedRouteTable: {
        id: virtualWanHubConnectionAssociatedRouteTable
      }
      propagatedRouteTables: {
        ids: virtualWanHubConnectionPropogatedRouteTables
        labels: virtualWanHubConnectionPropogatedLabels
        }
    
    } : {}
```

Let me know if you want me to create a PR for this - i have not managed to test this code when routing intent is not enabled.

## To Reproduce

Steps to reproduce the behaviour:

1. Deploy vWAN with routing intent enabled.
2. Run the example VWAN scenario.

## Expected behaviour

The virtual network connection should be routing intent aware 

## Correlation ID

`73196261-75d5-4aa8-a426-aeed9e2a7230`

**Comment by MilesCameron-DMs** [comment]
Didn't want to create the PR if there is already something in the pipeline but let me know if you want me to.

For review before raising the PR: https://github.com/MilesCameron-DMs/bicep-lz-vending

**Comment by jtracey93** [comment]
Please PR. Code looks great @MilesCameron-DMs 👍👍
