### ISSUE TITLE
🪲 1.5.1 breaking change (maybe) 

### ISSUE THREAD

**Issue by tssdavey** [Azure/bicep-lz-vending#63]
## Describe the bug

I get this error when using version 1.5.1
```
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "target": "/providers/Microsoft.Management/managementGroups/xenia-corp/providers/Microsoft.Resources/deployments/shared-services",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
        "details": [
            {
                "code": "ResourceDeploymentFailure",
                "target": "/providers/Microsoft.Management/managementGroups/xenia-corp/providers/Microsoft.Resources/deployments/lz-vend-sub-res-create-shared-services-i7ug2kbzlb7vc",
                "message": "The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.",
                "details": [
                    {
                        "code": "DeploymentOutputEvaluationFailed",
                        "target": "/providers/Microsoft.Management/managementGroups/xenia-corp/providers/Microsoft.Resources/deployments/lz-vend-sub-res-create-shared-services-i7ug2kbzlb7vc",
                        "message": "Unable to evaluate template outputs: 'failedFeatures'. Please see error details and deployment operations. Please see https://aka.ms/arm-common-errors for usage details.",
                        "details": [
                            {
                                "code": "DeploymentOutputEvaluationFailed",
                                "target": "failedFeatures",
                                "message": "The template output 'failedFeatures' is not valid: The language expression property 'failedFeaturesRegistrations' doesn't exist, available properties are 'failedProvidersRegistrations'.."
                            }
                        ]
                    }
                ]
            }
        ]
    }
}
```

## To Reproduce

Steps to reproduce the behaviour:

```
targetScope = 'managementGroup'

module subscriptionmod 'br/public:lz/sub-vending:1.5.1' = {
  name: '<my-name>'
  params: {
    subscriptionAliasEnabled: true
    subscriptionBillingScope: '<my billing scope>'
    subscriptionAliasName: '<my-name>'
    subscriptionDisplayName: '<my-name>'
    subscriptionWorkload: 'Production'
    subscriptionManagementGroupAssociationEnabled: true
    subscriptionManagementGroupId: '<my-mg>'
  }
}
```

results in above error

```
module subscriptionmod 'br/public:lz/sub-vending:1.4.1' = {
  name: '<my-name>'
  params: {
    subscriptionAliasEnabled: true
    subscriptionBillingScope: '<my billing scope>'
    subscriptionAliasName: '<my-name>'
    subscriptionDisplayName: '<my-name>'
    subscriptionWorkload: 'Production'
    subscriptionManagementGroupAssociationEnabled: true
    subscriptionManagementGroupId: '<my-mg>'
  }
}
```

results in successful deployment  

## Additional context

I'm happy to try and look into this one myself

**Comment by jtracey93** [comment]
Thanks for raising @tssdavey.

Can you confirm what bicep version you have installed? Are you on the latest?

`az bicep version`
`bicep --version`

> Note it can be installed side-by-side so you need to check and ensure both are up-to-date

![image](https://github.com/Azure/bicep-lz-vending/assets/41163455/faf5eae8-e9f2-4ef7-9b69-461b538f0b45)

**Comment by tssdavey** [comment]
0.24.24
![image](https://github.com/Azure/bicep-lz-vending/assets/54796226/cd4aecf0-e16c-40fa-9062-db4d26940d1f)

**Comment by sebassem** [comment]
@tssdavey Thanks for submitting this issue, it should be fixed in the assigned PR.

**Comment by MilesCameron-DMs** [comment]
I am also seeing this issue.

**Comment by dburlinson** [comment]
I am having the same issue. The sooner this PR can fix the better.

**Comment by sebassem** [comment]
We are working to merge this asap. Not to get you blocked, you can just replace _Invoke-RegisterSubscriptionResourceProviders.ps1_ with the [version in the PR](https://github.com/Azure/bicep-lz-vending/blob/7c32401cceecc9799f6e30ce280c03a4227bea7f/src/scripts/Invoke-RegisterSubscriptionResourceProviders.ps1) to get this resolved.

**Comment by dburlinson** [comment]
For what it's worth I just reverted to using v1.4.1 of the module and it works a-ok.

**Comment by PierreCo31** [comment]
Still having the issue, is this module still maintained since the move to AVM ?

**Comment by jtracey93** [comment]
This is indeed maintained. We are so close to getting the AVM module out with this fix in. 

Cc: @sebassem

**Comment by Zalmez** [comment]
Any ETA when the branch will be merged?

**Comment by sebassem** [comment]
ETA is mid-ext week, we are pending final reviews from the AVM team.

**Comment by sebassem** [comment]
we have finally published the [AVM module for sub-vending](https://aka.ms/lz-vending/bicep), thanks for your patience. Please review the announcement [here ](https://github.com/Azure/bicep-lz-vending)on how to move forward.
