### ISSUE TITLE
❓👂 Question/Feedback - Guidance On Adding Resources That Can be Consumed By Workload Teams

### ISSUE THREAD

**Issue by bzabber** [Azure/bicep-lz-vending#67]
## Question/Feedback

I don't see a pattern in the documentation (perhaps it's not obvious), for how I can add some common fixtures in subscriptions that can be used by Application teams. Ex: Resource Group for a KeyVault, Resource Group for Storage Accounts, Recovery Vaults and so on.

In my case the subscriptions already exist and I see there's an example to accommodate adding the networking and peering.

What would I need to do to extend that a bit to include the resources I mentioned above?

## Possible Answers/Solutions?

I'd like to follow a recommended pattern so that it doesn't break away too much from the LZ-Vending approach. (I'd like to reuse, leverage the existing automation as much as possible found in the repo.)

**Comment by sebassem** [comment]
Hi @bzabber, apologies for the late reply. The problem with this approach is that there will be no limit on what we can add to the subscription so it's better to leave it up to the application teams to deploy their own resources as they see fit. If you want, you can follow the pattern we used to deploy the deployment script responsible for registering the resource providers on the subscription.
