### ISSUE TITLE
❓👂 Question - Testing out subscription vending

### ISSUE THREAD

**Issue by arrerezai** [Azure/bicep-lz-vending#74]
## Question

Hi, 

I am fairly new to subscription/lz vending and would very much like to try it out as I most likely think that my customer would love to automate the e2e process for the application teams. However, at this point I wonder, is there any easy way to try the concept out? 

I tried to follow example 1, which led to the following error message "User is not authorized to create subscriptions on this enrollment account", which made me realize I need an account on the EA side be it an SPN or whatever to allow me to create subscriptions. Is there like a detailed step-by-step guide to follow in order to follow along and get some more insights?
I've found one customer over Medium who achieved to make a nice subscription vending solution, but their articles are mainly on a conceptual level rather than on a detailed level, which I believe is what I am looking for...

What I loved in the ALZ Bicep series where the sessions with real examples - Do you @jtracey93 and the team maybe have in the pipeline to record a session where you provide a real example of subscription vending e2e too?

Thanks!

**Comment by MilesCameron-DMs** [comment]
Regarding the error message you got, this may be covered here : https://github.com/azure/bicep-lz-vending/wiki/permissions

**Comment by sebassem** [comment]
@arrerezai sorry it took a while to respond, do you still face the same problem after reviewing the [article shared above](https://github.com/azure/bicep-lz-vending/wiki/permissions) ?

**Comment by arrerezai** [comment]
Hi @MilesCameron-DMs and @sebassem , 
Thanks for replying to my question. I wasn't really looking to solve any problem, as I'm stating in my summary that the error message led me to some new understandings. I was curious to know if there is some written documentation on a step-by-step basis for subscription vending implementation (like a how-to) or else if the gentlemen behind the similar initiatives could maybe create a session based on real examples? 
Anyway, since subscription vending is finally part of AVM, I am more keen into get that up and working.

**Comment by sebassem** [comment]
While there are no current plans to do a video, we can plan to do one in the near future. This is the closest we have to a [step-by-step video](https://youtu.be/hu0PgCamxt0?t=1038)

**Comment by arrerezai** [comment]
Thanks, seen that already, would be awesome to have something more detailed/practical/hands-on. Anyway, closing this now as reportedly will pursue with the brand new AVM module.
